// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Movies.Application.Data;

#nullable disable

namespace Movies.Application.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Movies.Application.Models.Movie", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Genres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("YearOfRelease")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6c8d365b-09e8-423c-b7d7-54f1863e6adb"),
                            Genres = "[\"a\",\"b\"]",
                            Title = "C# Hero",
                            YearOfRelease = 2010
                        },
                        new
                        {
                            Id = new Guid("3eed0ee4-a18f-4e09-8680-16b1ad4b5c78"),
                            Genres = "[\"a\",\"b\"]",
                            Title = "C# Pro",
                            YearOfRelease = 2010
                        },
                        new
                        {
                            Id = new Guid("5c37b1a0-7a1a-4f62-9741-e519cdd62dc7"),
                            Genres = "[\"a\",\"b\"]",
                            Title = "C#",
                            YearOfRelease = 2010
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
